const testTasks = [
  {
    id: 0,
    title: 'Bug fixing',
    priority: 'high',
    category: 'IT',
    createdAt: 1657548503635,
    dueDate: new Date(1657628551554),
    user: [
      {
        name: 'Michael',
        icon: './img/github.jpg',
        mail: 'michael@gmail.net',
      },
    ],
    status: 'to-do',
    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Velit accusamus debitis veniam!',
    color: 'lightblue',
    locationTask: 'board',
  },
  {
    id: 1,
    title: 'Create test process',
    priority: 'medium',
    category: 'IT',
    createdAt: 1657548520490,
    dueDate: new Date(1657628551554),
    user: [
      {
        name: 'Stefan',
        icon: './img/001_fb copy.jpg',
        mail: 'stefan@gmail.net',
      },
    ],
    status: 'in-progress',
    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Velit accusamus debitis veniam!',
    color: 'lightblue',
    locationTask: 'board',
  },
  {
    id: 2,
    title: 'Cost calculation',
    priority: 'medium',
    category: 'Management',
    createdAt: 1657548542366,
    dueDate: new Date(1657628551554),
    user: [
      {
        name: 'Sahra',
        icon: './img/icon_female_6.png',
        mail: 'sahra@gmail.net',
      },
    ],
    status: 'testing',
    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Velit accusamus debitis veniam!',
    color: 'lightblue',
    locationTask: 'board',
  },
  {
    id: 3,
    title: 'Create new slogan',
    priority: 'medium',
    category: 'Marketing',
    createdAt: 1657548551554,
    dueDate: new Date(1657628551554),
    user: [
      {
        name: 'Sven',
        icon: './img/icon_male_2.png',
        mail: 'sven@gmail.net',
      },
    ],
    status: 'done',
    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Velit accusamus debitis veniam!',
    color: 'lightblue',
    locationTask: 'board',
  },
  {
    id: 4,
    title: 'Plan a special sales event',
    priority: 'high',
    category: 'Sales',
    createdAt: 1657548580054,
    dueDate: new Date(1657628551554),
    user: [
      {
        name: 'Stefan',
        icon: './img/001_fb copy.jpg',
        mail: 'stefan@gmail.net',
      },
      {
        name: 'Michael',
        icon: './img/github.jpg',
        mail: 'michael@gmail.net',
      },
    ],
    status: 'to-do',
    description: 'ID 4 Lorem ipsum dolor sit amet, consectetur adipisicing elit. Velit accusamus debitis veniam!',
    color: 'lightblue',
    locationTask: 'board',
  },
  {
    id: 5,
    title: 'Plan company event',
    priority: 'high',
    category: 'Sales',
    createdAt: 1657548580054,
    dueDate: new Date(1657628551554),
    user: [
      {
        name: 'Michael',
        icon: './img/github.jpg',
        mail: 'michael@gmail.net',
      },
    ],
    status: 'to-do',
    description: 'Lorem Test',
    color: 'lightblue',
    locationTask: 'backlog',
  },
  {
    id: 6,
    title: 'Calculation of the sales last quarter',
    priority: 'medium',
    category: 'Sales',
    createdAt: 1657548580054,
    dueDate: new Date(1657628551554),
    user: [
      {
        name: 'Michael',
        icon: './img/github.jpg',
        mail: 'michael@gmail.net',
      },
    ],
    status: 'to-do',
    description: 'ID 4 Lorem ipsum dolor sit amet, consectetur adipisicing elit. Velit accusamus debitis veniam!',
    color: 'lightblue',
    locationTask: 'backlog',
  }
  ,
  {
    id: 7,
    title: 'Create Login Area',
    priority: 'medium',
    category: 'IT',
    createdAt: 1657548580054,
    dueDate: new Date(1697735551554),
    user: [
      {
        name: 'Testuser',
        icon: './img/icon-unknown.svg',
        mail: 'testuser@gmail.net',
      },
    ],
    status: 'to-do',
    description: 'ID 4 Lorem ipsum dolor sit amet, consectetur adipisicing elit. Velit accusamus debitis veniam!',
    color: 'lightblue',
    locationTask: 'backlog',
  }
  ,
  {
    id: 8,
    title: 'Calculation of the sales last quarter',
    priority: 'medium',
    category: 'Sales',
    createdAt: 1657548580054,
    dueDate: new Date(1697732551554),
    user: [
      {
        name: 'Testuser',
        icon: './img/icon-unknown.svg',
        mail: 'testuser@gmail.net',
      },
    ],
    status: 'done',
    description: 'ID 4 Lorem ipsum dolor sit amet, consectetur adipisicing elit. Velit accusamus debitis veniam!',
    color: 'lightblue',
    locationTask: 'board',
  },
  {
    id: 9,
    title: 'Report of Q3',
    priority: 'medium',
    category: 'Sales',
    createdAt: 1657548580054,
    dueDate: new Date(1678730551554),
    user: [
      {
        name: 'Testuser',
        icon: './img/icon-unknown.svg',
        mail: 'testuser@gmail.net',
      },
    ],
    status: 'in-progress',
    description: 'ID 4 Lorem ipsum dolor sit amet, consectetur adipisicing elit. Velit accusamus debitis veniam!',
    color: 'lightblue',
    locationTask: 'board',
  },
  {
    id: 10,
    title: 'Kickoff Project Rapid',
    priority: 'medium',
    category: 'Management',
    createdAt: 1657548580054,
    dueDate: new Date(1687729551554),
    user: [
      {
        name: 'Testuser',
        icon: './img/icon-unknown.svg',
        mail: 'testuser@gmail.net',
      },
    ],
    status: 'to-do',
    description: 'ID 4 Lorem ipsum dolor sit amet, consectetur adipisicing elit. Velit accusamus debitis veniam!',
    color: 'lightblue',
    locationTask: 'board',
  },
];

let colorPicker = ['picker1', 'picker2', 'picker3', 'picker4', 'picker5', 'picker6'];
